version: '2.1'
services:
  de-selenium:
    image: selenium/standalone-chrome:latest
    container_name: de-selenium
    shm_size: 2gb
    environment:
      - SE_START_XVFB=false
      - SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP=true
    ports:
      - "4444:4444"
    networks:
      - dataease-network